### ISSUE TITLE
VFA17SCM27O adding last name

### ISSUE THREAD

**Issue by VFA17SCM27O** [SPM587FA17/SCM587FA17#419]

**Comment by VFA17SCM27O** [comment]
@SPM587FA17 to prevent pushing to the master branch, you could have made it protected

**Comment by SPM587FA17** [comment]
It’s like this for a reason.

Sent from my iPhone

On Nov 15, 2017, at 9:40 PM, Vadym Ovcharenko <notifications@github.com> wrote:

@SPM587FA17 to prevent pushing to the master branch, you could have made it protected
